{"name": "test_TS_002", "status": "passed", "attachments": [{"name": "Error with xyzabc123", "source": "ef2bdd78-02ac-462c-b8f8-cf3b33869678-attachment.png", "type": "image/png"}, {"name": "Error at<class 'TC_LF_004.Test_invalid_pass'>", "source": "ce413903-cf3f-4f42-b967-42793bc9b7f7-attachment.png", "type": "image/png"}, {"name": "Validation error occurred....", "source": "0b82381a-7160-40f6-81b4-04332fdb8b93-attachment.png", "type": "image/png"}, {"name": "log", "source": "ff5cbb6c-171d-4379-890a-516f54ebda06-attachment.txt", "type": "text/plain"}], "start": 1740900132014, "stop": 1740900136876, "uuid": "742950ba-2452-4977-a849-6789e6df7491", "historyId": "1e00eadf4f436c91f83617f5a014dfd4", "testCaseId": "1e00eadf4f436c91f83617f5a014dfd4", "fullName": "testCases.Login  Test Cases.TC_LF_004.Test_invalid_pass#test_TS_002", "labels": [{"name": "parentSuite", "value": "testCases.Login  Test Cases"}, {"name": "suite", "value": "TC_LF_004"}, {"name": "subSuite", "value": "Test_invalid_pass"}, {"name": "host", "value": "DESKTOP-DL1JSBI"}, {"name": "thread", "value": "12792-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.Login  Test Cases.TC_LF_004"}]}