{"name": "test_data_driven_testing[test300@mailinator.com-test@143-Valid]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_004_DDT.Test_Data_Driven object at 0x000001D6176BBA40>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"8968519c947b8a3251f87f9a7de6c9f2\")>, username = 'test300@mailinator.com'\npassword = 'test@143', expected_result = 'Valid'\n\n    @pytest.mark.parametrize(\"username, password, expected_result\", get_exceldata(path, \"Sheet1\"))\n    def test_data_driven_testing(self, setup, username, password, expected_result):\n        self.logger.info(\"**** Setting up the browser ****\")\n    \n        self.driver = setup\n        self.driver.maximize_window()\n    \n        try:\n            # Navigate to Login Page\n            self.driver.get(self.baseurl)\n            self.hp = Homepage(self.driver)\n            self.hp.clickmyaccount()\n            self.hp.clicklogin()\n            self.ma = My_Account_page(self.driver)\n    \n            # Perform Login\n            self.lp = Login(self.driver)\n            self.lp.click_email(username)\n            self.lp.click_password(password)\n            self.lp.click_login()\n    \n            # Initialize actual_result to avoid AttributeError\n            self.actual_result = self.lp.myaccount_page()\n            self.result = self.actual_result.strip().lower()\n    \n            if self.result == expected_result:\n                self.logger.info(\n                    f\"Test Passed for {username}: Expected = {expected_result}, Got = {self.actual_result}\")\n                assert True\n            else:\n                self.logger.error(\n                    f\"Test Failed for {username}: Expected = {expected_result}, Got = {self.actual_result}\")\n                allure.attach(self.driver.get_screenshot_as_png(), name=\"Test_Failure\",\n                              attachment_type=AttachmentType.PNG)\n>               assert False\nE               assert False\n\ntestCases\\Data Driven Test\\test_004_DDT.py:55: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_004_DDT.Test_Data_Driven object at 0x000001D6176BBA40>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"8968519c947b8a3251f87f9a7de6c9f2\")>, username = 'test300@mailinator.com'\npassword = 'test@143', expected_result = 'Valid'\n\n    @pytest.mark.parametrize(\"username, password, expected_result\", get_exceldata(path, \"Sheet1\"))\n    def test_data_driven_testing(self, setup, username, password, expected_result):\n        self.logger.info(\"**** Setting up the browser ****\")\n    \n        self.driver = setup\n        self.driver.maximize_window()\n    \n        try:\n            # Navigate to Login Page\n            self.driver.get(self.baseurl)\n            self.hp = Homepage(self.driver)\n            self.hp.clickmyaccount()\n            self.hp.clicklogin()\n            self.ma = My_Account_page(self.driver)\n    \n            # Perform Login\n            self.lp = Login(self.driver)\n            self.lp.click_email(username)\n            self.lp.click_password(password)\n            self.lp.click_login()\n    \n            # Initialize actual_result to avoid AttributeError\n            self.actual_result = self.lp.myaccount_page()\n            self.result = self.actual_result.strip().lower()\n    \n            if self.result == expected_result:\n                self.logger.info(\n                    f\"Test Passed for {username}: Expected = {expected_result}, Got = {self.actual_result}\")\n                assert True\n            else:\n                self.logger.error(\n                    f\"Test Failed for {username}: Expected = {expected_result}, Got = {self.actual_result}\")\n                allure.attach(self.driver.get_screenshot_as_png(), name=\"Test_Failure\",\n                              attachment_type=AttachmentType.PNG)\n                assert False\n        except Exception as e:\n            self.logger.error(f\"Unexpected error during validation: {e}\")\n            allure.attach(self.driver.get_screenshot_as_png(), name=\"Unexpected_Error\",\n                          attachment_type=AttachmentType.PNG)\n>           assert False\nE           assert False\n\ntestCases\\Data Driven Test\\test_004_DDT.py:60: AssertionError"}, "attachments": [{"name": "Test_Failure", "source": "9d95b6db-77c3-4a20-9a0b-846af2125e1c-attachment.png", "type": "image/png"}, {"name": "Unexpected_Error", "source": "3fba49a8-c150-464a-9ecd-b138c82f7b7c-attachment.png", "type": "image/png"}, {"name": "log", "source": "65393072-6fe9-46e9-ba57-548200f63ae8-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'test300@mailinator.com'"}, {"name": "password", "value": "'test@143'"}, {"name": "expected_result", "value": "'Valid'"}], "start": 1740907627319, "stop": 1740907636100, "uuid": "9464106c-d55e-4055-b547-03f82c551bb4", "historyId": "3f621fecf7541fd151a3a2d8badc9ac6", "testCaseId": "feaf2845cd517faac78063da184e07ae", "fullName": "testCases.Data Driven Test.test_004_DDT.Test_Data_Driven#test_data_driven_testing", "labels": [{"name": "parentSuite", "value": "testCases.Data Driven Test"}, {"name": "suite", "value": "test_004_DDT"}, {"name": "subSuite", "value": "Test_Data_Driven"}, {"name": "host", "value": "DESKTOP-DL1JSBI"}, {"name": "thread", "value": "4448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.Data Driven Test.test_004_DDT"}]}