{"name": "test_data_driven_testing[ndj@mailinator.com-a4iM2@qJaP7U4AS-Valid]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_004_DDT.Test_Data_Driven object at 0x000001D6175CCDA0>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"8c75c272823f474b235d7f71b67a8454\")>, username = 'ndj@mailinator.com'\npassword = 'a4iM2@qJaP7U4AS', expected_result = 'Valid'\n\n    @pytest.mark.parametrize(\"username, password, expected_result\", get_exceldata(path, \"Sheet1\"))\n    def test_data_driven_testing(self, setup, username, password, expected_result):\n        self.logger.info(\"**** Setting up the browser ****\")\n    \n        self.driver = setup\n        self.driver.maximize_window()\n    \n        try:\n            # Navigate to Login Page\n            self.driver.get(self.baseurl)\n            self.hp = Homepage(self.driver)\n            self.hp.clickmyaccount()\n            self.hp.clicklogin()\n            self.ma = My_Account_page(self.driver)\n    \n            # Perform Login\n            self.lp = Login(self.driver)\n            self.lp.click_email(username)\n            self.lp.click_password(password)\n            self.lp.click_login()\n    \n            # Initialize actual_result to avoid AttributeError\n            self.actual_result = self.lp.myaccount_page()\n            self.result = self.actual_result.strip().lower()\n    \n            if self.result == expected_result:\n                self.logger.info(\n                    f\"Test Passed for {username}: Expected = {expected_result}, Got = {self.actual_result}\")\n                assert True\n            else:\n                self.logger.error(\n                    f\"Test Failed for {username}: Expected = {expected_result}, Got = {self.actual_result}\")\n                allure.attach(self.driver.get_screenshot_as_png(), name=\"Test_Failure\",\n                              attachment_type=AttachmentType.PNG)\n>               assert False\nE               assert False\n\ntestCases\\Data Driven Test\\test_004_DDT.py:55: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_004_DDT.Test_Data_Driven object at 0x000001D6175CCDA0>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"8c75c272823f474b235d7f71b67a8454\")>, username = 'ndj@mailinator.com'\npassword = 'a4iM2@qJaP7U4AS', expected_result = 'Valid'\n\n    @pytest.mark.parametrize(\"username, password, expected_result\", get_exceldata(path, \"Sheet1\"))\n    def test_data_driven_testing(self, setup, username, password, expected_result):\n        self.logger.info(\"**** Setting up the browser ****\")\n    \n        self.driver = setup\n        self.driver.maximize_window()\n    \n        try:\n            # Navigate to Login Page\n            self.driver.get(self.baseurl)\n            self.hp = Homepage(self.driver)\n            self.hp.clickmyaccount()\n            self.hp.clicklogin()\n            self.ma = My_Account_page(self.driver)\n    \n            # Perform Login\n            self.lp = Login(self.driver)\n            self.lp.click_email(username)\n            self.lp.click_password(password)\n            self.lp.click_login()\n    \n            # Initialize actual_result to avoid AttributeError\n            self.actual_result = self.lp.myaccount_page()\n            self.result = self.actual_result.strip().lower()\n    \n            if self.result == expected_result:\n                self.logger.info(\n                    f\"Test Passed for {username}: Expected = {expected_result}, Got = {self.actual_result}\")\n                assert True\n            else:\n                self.logger.error(\n                    f\"Test Failed for {username}: Expected = {expected_result}, Got = {self.actual_result}\")\n                allure.attach(self.driver.get_screenshot_as_png(), name=\"Test_Failure\",\n                              attachment_type=AttachmentType.PNG)\n                assert False\n        except Exception as e:\n            self.logger.error(f\"Unexpected error during validation: {e}\")\n            allure.attach(self.driver.get_screenshot_as_png(), name=\"Unexpected_Error\",\n                          attachment_type=AttachmentType.PNG)\n>           assert False\nE           assert False\n\ntestCases\\Data Driven Test\\test_004_DDT.py:60: AssertionError"}, "attachments": [{"name": "Test_Failure", "source": "ca398bd7-d7d8-4e44-b18b-98a79be7f2ea-attachment.png", "type": "image/png"}, {"name": "Unexpected_Error", "source": "9d533b88-f30f-4d98-b04e-11339226e3b2-attachment.png", "type": "image/png"}, {"name": "log", "source": "ebe5f448-2c89-4f0b-892e-34d401d8dc64-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'ndj@mailinator.com'"}, {"name": "password", "value": "'a4iM2@qJaP7U4AS'"}, {"name": "expected_result", "value": "'Valid'"}], "start": 1740907587452, "stop": 1740907596136, "uuid": "dabba0a4-c0d9-472c-9a31-e4b102288830", "historyId": "5824f2dfec43c90d8f7bae3ad7be7a74", "testCaseId": "feaf2845cd517faac78063da184e07ae", "fullName": "testCases.Data Driven Test.test_004_DDT.Test_Data_Driven#test_data_driven_testing", "labels": [{"name": "parentSuite", "value": "testCases.Data Driven Test"}, {"name": "suite", "value": "test_004_DDT"}, {"name": "subSuite", "value": "Test_Data_Driven"}, {"name": "host", "value": "DESKTOP-DL1JSBI"}, {"name": "thread", "value": "4448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.Data Driven Test.test_004_DDT"}]}