{"name": "test_data_driven_testing[test300@mailinator.com-test@143-Valid]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_004_DDT.Test_Data_Driven object at 0x0000023F684D38C0>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a09793674c61d8ce9ec40f3f4157e80e\")>, username = 'test300@mailinator.com'\npassword = 'test@143', expected_result = 'Valid'\n\n    @pytest.mark.parametrize(\"username, password, expected_result\", get_exceldata(path, \"Sheet1\"))\n    def test_data_driven_testing(self, setup, username, password, expected_result):\n        self.logger.info(f\"Starting test for: {username}\")\n    \n        self.driver = setup\n        self.driver.maximize_window()\n    \n        try:\n            # Navigate to Login Page\n            self.driver.get(self.baseurl)\n            self.hp = Homepage(self.driver)\n            self.hp.clickmyaccount()\n            self.hp.clicklogin()\n            self.ma = My_Account_page(self.driver)\n    \n            # Perform Login\n            self.lp = Login(self.driver)\n            self.lp.click_email(username)\n            self.lp.click_password(password)\n            self.lp.click_login()\n    \n            # Capture Screenshot after Login\n            allure.attach(self.driver.get_screenshot_as_png(), name=f\"After_Login_{username}\",\n                          attachment_type=AttachmentType.PNG)\n    \n            # Validate Result\n            self.actual_result = self.lp.myaccount_page()\n            self.logger.info(f\"Actual: {self.actual_result}, Expected: {expected_result}\")\n    \n            # Assert and Capture Failures\n            if self.actual_result.strip().lower() == expected_result.strip().lower():\n                self.logger.info(f\"Test Passed for {username}\")\n                assert True\n            else:\n                self.logger.error(f\"Test Failed for {username}\")\n                allure.attach(self.driver.get_screenshot_as_png(), name=f\"Failure_{username}\",\n                              attachment_type=AttachmentType.PNG)\n>               assert False\nE               assert False\n\ntestCases\\Data Driven Test\\test_004_DDT.py:57: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_004_DDT.Test_Data_Driven object at 0x0000023F684D38C0>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a09793674c61d8ce9ec40f3f4157e80e\")>, username = 'test300@mailinator.com'\npassword = 'test@143', expected_result = 'Valid'\n\n    @pytest.mark.parametrize(\"username, password, expected_result\", get_exceldata(path, \"Sheet1\"))\n    def test_data_driven_testing(self, setup, username, password, expected_result):\n        self.logger.info(f\"Starting test for: {username}\")\n    \n        self.driver = setup\n        self.driver.maximize_window()\n    \n        try:\n            # Navigate to Login Page\n            self.driver.get(self.baseurl)\n            self.hp = Homepage(self.driver)\n            self.hp.clickmyaccount()\n            self.hp.clicklogin()\n            self.ma = My_Account_page(self.driver)\n    \n            # Perform Login\n            self.lp = Login(self.driver)\n            self.lp.click_email(username)\n            self.lp.click_password(password)\n            self.lp.click_login()\n    \n            # Capture Screenshot after Login\n            allure.attach(self.driver.get_screenshot_as_png(), name=f\"After_Login_{username}\",\n                          attachment_type=AttachmentType.PNG)\n    \n            # Validate Result\n            self.actual_result = self.lp.myaccount_page()\n            self.logger.info(f\"Actual: {self.actual_result}, Expected: {expected_result}\")\n    \n            # Assert and Capture Failures\n            if self.actual_result.strip().lower() == expected_result.strip().lower():\n                self.logger.info(f\"Test Passed for {username}\")\n                assert True\n            else:\n                self.logger.error(f\"Test Failed for {username}\")\n                allure.attach(self.driver.get_screenshot_as_png(), name=f\"Failure_{username}\",\n                              attachment_type=AttachmentType.PNG)\n                assert False\n    \n        except Exception as e:\n            self.logger.error(f\"Unexpected error: {e}\")\n            allure.attach(self.driver.get_screenshot_as_png(), name=f\"Unexpected_Error_{username}\",\n                          attachment_type=AttachmentType.PNG)\n>           assert False\nE           assert False\n\ntestCases\\Data Driven Test\\test_004_DDT.py:63: AssertionError"}, "attachments": [{"name": "After_Login_test300@mailinator.com", "source": "7975e5f1-bca8-46e8-baef-c3c6ac0a2586-attachment.png", "type": "image/png"}, {"name": "Failure_test300@mailinator.com", "source": "fe517afe-287a-4d8f-a955-65ca0c14c6de-attachment.png", "type": "image/png"}, {"name": "Unexpected_Error_test300@mailinator.com", "source": "5cf256b1-8d32-4dfc-9827-07a779f5e36e-attachment.png", "type": "image/png"}, {"name": "log", "source": "b648d9df-4151-4c06-9210-b3cbcd1c760d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'test300@mailinator.com'"}, {"name": "password", "value": "'test@143'"}, {"name": "expected_result", "value": "'Valid'"}], "start": 1740908766202, "stop": 1740908784263, "uuid": "56a61149-526d-4e23-834f-c91da73b83f8", "historyId": "3f621fecf7541fd151a3a2d8badc9ac6", "testCaseId": "feaf2845cd517faac78063da184e07ae", "fullName": "testCases.Data Driven Test.test_004_DDT.Test_Data_Driven#test_data_driven_testing", "labels": [{"name": "parentSuite", "value": "testCases.Data Driven Test"}, {"name": "suite", "value": "test_004_DDT"}, {"name": "subSuite", "value": "Test_Data_Driven"}, {"name": "host", "value": "DESKTOP-DL1JSBI"}, {"name": "thread", "value": "4184-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.Data Driven Test.test_004_DDT"}]}